apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
    - name: volume
      image: debian
      command: ["/bin/sh"]
      args: ["-c", "while true ;do  date >/data/out; sleep 1; done"]
      volumeMounts:
        - mountPath: /data
          name: test-volume
  volumes:
    - name: test-volume
      hostPath:
        path: /data
        type: Directory