apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
spec:
  containers:
    - name: busybox
      image: alpine
      command: [ "/bin/sh", "-c" ]
      args:
        - |
          apk add --no-cache curl bind-tools &&
          while true; do sleep 30; done;

