apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command: [ "/bin/sh", "-c" ]
      args:
        - |
          apk update &&
          apk add curl bind-tools &&
          while true; do sleep 30; done;
